// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomManagementMicroservice.Data;

namespace RoomManagementMicroservice.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210511163056_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2");

            modelBuilder.Entity("RoomManagementMicroservice.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facilities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonsNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomCategory")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Comfort, style and functionality are the words that can describe our standard double rooms. Hotel Iasi Royal Residence invites you to enjoy your stay in a spacious room with a QueenSize double bed and a spacious balcony where you can enjoy your morning coffee.",
                            Facilities = "Free Wi-Fi, Air Conditioning System",
                            Image = "standard0.jpg",
                            PersonsNumber = 2,
                            Price = 150,
                            RoomCategory = "Standard",
                            RoomNumber = 100,
                            State = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comfort, style and functionality are the words that can describe our standard triple rooms. Hotel Iasi Royal Residence invites you to enjoy your stay in a spacious room with a QueenSize double bed, a single bed and a spacious balcony where you can enjoy your morning coffee.",
                            Facilities = "Free Wi-Fi, Air Conditioning System",
                            Image = "standard1.jpg",
                            PersonsNumber = 3,
                            Price = 180,
                            RoomCategory = "Standard",
                            RoomNumber = 101,
                            State = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Comfort, style and functionality are the words that can describe our standard double rooms. Hotel Iasi Royal Residence invites you to enjoy your stay in a spacious room with a QueenSize double bed and a spacious balcony where you can enjoy your morning coffee.",
                            Facilities = "Free Wi-Fi, Air Conditioning System",
                            Image = "standard2.jpg",
                            PersonsNumber = 2,
                            Price = 150,
                            RoomCategory = "Standard",
                            RoomNumber = 102,
                            State = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comfort, style and functionality are the words that can describe our standard double rooms. Hotel Iasi Royal Residence invites you to enjoy your stay in a spacious room with a QueenSize double bed and a spacious balcony where you can enjoy your morning coffee.",
                            Facilities = "Free Wi-Fi, Air Conditioning System",
                            Image = "standard0.jpg",
                            PersonsNumber = 2,
                            Price = 150,
                            RoomCategory = "Standard",
                            RoomNumber = 103,
                            State = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Comfort, style and functionality are the words that can describe our standard triple rooms. Hotel Iasi Royal Residence invites you to enjoy your stay in a spacious room with a QueenSize double bed, a single bed and a spacious balcony where you can enjoy your morning coffee.",
                            Facilities = "Free Wi-Fi, Air Conditioning System",
                            Image = "standard1.jpg",
                            PersonsNumber = 3,
                            Price = 180,
                            RoomCategory = "Standard",
                            RoomNumber = 104,
                            State = "Available"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Deluxe Room is the answer to your expectations from our hotel room. The surface of 22 sqm with a maximum capacity of 2 people, is decorated in a minimalist style with a lot of good taste, and the room is flooded with light through the generous window it has.The stylish, non-smoking room is equipped with a queen size bed and a flat - screen TV with international channels.Bathrobes and slippers are available for added comfort.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast",
                            Image = "deluxe0.jpg",
                            PersonsNumber = 2,
                            Price = 200,
                            RoomCategory = "Deluxe",
                            RoomNumber = 200,
                            State = "Available"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Deluxe Room is the answer to your expectations from our hotel room. The surface of 22 sqm with a maximum capacity of 2 people, is decorated in a minimalist style with a lot of good taste, and the room is flooded with light through the generous window it has.The stylish, non-smoking room is equipped with a queen size bed and a flat - screen TV with international channels.Bathrobes and slippers are available for added comfort.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast",
                            Image = "deluxe1.jpg",
                            PersonsNumber = 2,
                            Price = 200,
                            RoomCategory = "Deluxe",
                            RoomNumber = 201,
                            State = "Available"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Deluxe Room is the answer to your expectations from a hotel room.The surface of 22 sqm with a maximum capacity of 3 people, is decorated in a minimalist style with a lot of good taste, and the room is flooded with light through the generous window it has.The stylish, non-smoking room is equipped with a queen size bed, single bed and a flat-screen TV with international channels.Bathrobes and slippers are available for added comfort.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast",
                            Image = "deluxe2.jpg",
                            PersonsNumber = 3,
                            Price = 230,
                            RoomCategory = "Deluxe",
                            RoomNumber = 202,
                            State = "Available"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Deluxe Room is the answer to your expectations from our hotel room. The surface of 22 sqm with a maximum capacity of 2 people, is decorated in a minimalist style with a lot of good taste, and the room is flooded with light through the generous window it has.The stylish, non-smoking room is equipped with a queen size bed and a flat - screen TV with international channels.Bathrobes and slippers are available for added comfort.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast",
                            Image = "deluxe0.jpg",
                            PersonsNumber = 2,
                            Price = 200,
                            RoomCategory = "Deluxe",
                            RoomNumber = 203,
                            State = "Available"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Deluxe Room is the answer to your expectations from a hotel room.The surface of 22 sqm with a maximum capacity of 3 people, is decorated in a minimalist style with a lot of good taste, and the room is flooded with light through the generous window it has.The stylish, non-smoking room is equipped with a queen size bed, single bed and a flat-screen TV with international channels.Bathrobes and slippers are available for added comfort.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast",
                            Image = "deluxe1.jpg",
                            PersonsNumber = 3,
                            Price = 230,
                            RoomCategory = "Deluxe",
                            RoomNumber = 204,
                            State = "Available"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Thoughtfully designed suite room.Two peaceful and spacious art deco rooms with King size four posture canopy bed &separate sitting and living room for 3 people.Offers a separate living area, private balcony overlooking the lush garden or lively town, flat screen TV with international channels and free WiFi.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast, Safe System",
                            Image = "suite0.jpg",
                            PersonsNumber = 3,
                            Price = 250,
                            RoomCategory = "Suite",
                            RoomNumber = 300,
                            State = "Available"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Thoughtfully designed suite room.Two peaceful and spacious art deco rooms with King size four posture canopy bed &separate sitting and living room for 4 people.Offers a separate living area, private balcony overlooking the lush garden or lively town, flat screen TV with international channels and free WiFi.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast, Safe System",
                            Image = "suite1.jpg",
                            PersonsNumber = 4,
                            Price = 280,
                            RoomCategory = "Suite",
                            RoomNumber = 301,
                            State = "Available"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Thoughtfully designed suite room.Two peaceful and spacious art deco rooms with King size four posture canopy bed &separate sitting and living room for 3 people.Offers a separate living area, private balcony overlooking the lush garden or lively town, flat screen TV with international channels and free WiFi.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast, Safe System",
                            Image = "suite2.jpg",
                            PersonsNumber = 3,
                            Price = 250,
                            RoomCategory = "Suite",
                            RoomNumber = 302,
                            State = "Available"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Thoughtfully designed suite room.Two peaceful and spacious art deco rooms with King size four posture canopy bed &separate sitting and living room for 4 people.Offers a separate living area, private balcony overlooking the lush garden or lively town, flat screen TV with international channels and free WiFi.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast, Safe System",
                            Image = "suite0.jpg",
                            PersonsNumber = 4,
                            Price = 280,
                            RoomCategory = "Suite",
                            RoomNumber = 303,
                            State = "Available"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Thoughtfully designed suite room.Two peaceful and spacious art deco rooms with King size four posture canopy bed &separate sitting and living room for 3 people.Offers a separate living area, private balcony overlooking the lush garden or lively town, flat screen TV with international channels and free WiFi.",
                            Facilities = "Free Wi-Fi, Air Conditioning System, Breakfast, Safe System",
                            Image = "suite1.jpg",
                            PersonsNumber = 3,
                            Price = 250,
                            RoomCategory = "Suite",
                            RoomNumber = 304,
                            State = "Available"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
