// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomManagementMicroservice.Data;

namespace RoomManagementMicroservice.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210420135543_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2");

            modelBuilder.Entity("RoomManagementMicroservice.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facilities")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonsNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomCategory")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "blabla",
                            Facilities = "Free Wi-Fi",
                            PersonsNumber = 2,
                            Price = 100,
                            RoomCategory = "Standard",
                            RoomNumber = 100,
                            State = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Description = "blabla",
                            Facilities = "Free Wi-Fi",
                            PersonsNumber = 3,
                            Price = 170,
                            RoomCategory = "Standard",
                            RoomNumber = 101,
                            State = "Booked"
                        },
                        new
                        {
                            Id = 3,
                            Description = "blabla",
                            Facilities = "Free Wi-Fi",
                            PersonsNumber = 3,
                            Price = 130,
                            RoomCategory = "Standard",
                            RoomNumber = 102,
                            State = "Booked"
                        },
                        new
                        {
                            Id = 4,
                            Description = "blabla",
                            Facilities = "Free Wi-Fi",
                            PersonsNumber = 2,
                            Price = 150,
                            RoomCategory = "Standard",
                            RoomNumber = 103,
                            State = "Booked"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
