// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomManagementMicroservice.Data;

namespace RoomManagementMicroservice.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2");

            modelBuilder.Entity("RoomManagementMicroservice.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonsNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new DateTime(2021, 4, 12, 22, 1, 8, 56, DateTimeKind.Local).AddTicks(7880),
                            CheckOut = new DateTime(2021, 4, 12, 22, 1, 8, 58, DateTimeKind.Local).AddTicks(6934),
                            PersonsNumber = 0,
                            RoomCategory = "Standard",
                            State = "Available",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new DateTime(2021, 4, 12, 22, 1, 8, 58, DateTimeKind.Local).AddTicks(8293),
                            CheckOut = new DateTime(2021, 4, 12, 22, 1, 8, 58, DateTimeKind.Local).AddTicks(8305),
                            PersonsNumber = 3,
                            RoomCategory = "Standard",
                            State = "Booked",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new DateTime(2021, 4, 12, 22, 1, 8, 58, DateTimeKind.Local).AddTicks(8308),
                            CheckOut = new DateTime(2021, 4, 12, 22, 1, 8, 58, DateTimeKind.Local).AddTicks(8311),
                            PersonsNumber = 3,
                            RoomCategory = "Standard",
                            State = "Booked",
                            UserId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
